services:
  - type: web
    name: ml-microservice
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 5001
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: false
    autoDeploy: true 